spring:
  application:
    name: user-ms
eureka:
 instance:
  hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      userService:
       failureRateThreshold: 50
       minimumNumberOfCalls: 5
       permittedNumberOfCallsInHalfOpenState: 3
       waitDurationInOpenState: 20s		
       automaticTransitionFromOpenToHalfOpenEnabled : true

management:
 tracing:
  sampling:
   probability: 1.0 

 zipkin:
  tracing:
   endpoint: http://localhost:9411/api/v2/spans

logging:
 pattern:
  level: "%5p [${spring.application.name:},%X{traceId},%X{spanId}]"
